export const STYLE_PRESETS = [
  {
    id: "classic",
    name: "Classic White",
    description: "واضح وبسيط لكل الفيديوهات",
    patch: {
      fontFamily: "Tajawal",
      color: "#FFFFFF",
      bg_enabled: true,
      bg_color: "#000000",
      bg_opacity: 0.55,
      shadow: 2,
      outline_enabled: false,
      caption_animation: "none",
    },
  },
  {
    id: "karaoke",
    name: "Karaoke Glow",
    description: "تأثير متحرك يبرز الكلمة الحالية",
    patch: {
      fontFamily: "Poppins",
      color: "#FFFFFF",
      bg_enabled: false,
      shadow: 3,
      caption_animation: "karaoke",
      karaoke_color: "#8B80FF",
    },
  },
  {
    id: "bold-yellow",
    name: "Bold Yellow",
    description: "ستايل ملفت لمحتوى السوشيال",
    patch: {
      fontFamily: "Bebas Neue",
      color: "#F7D84B",
      bg_enabled: true,
      bg_color: "#000000",
      bg_opacity: 0.45,
      shadow: 2,
      outline_enabled: true,
      outline_color: "#000000",
      caption_animation: "none",
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "خفيف وهادئ بدون عناصر كثيرة",
    patch: {
      fontFamily: "DM Sans",
      color: "#F4F6FA",
      bg_enabled: false,
      shadow: 1,
      outline_enabled: false,
      caption_animation: "fade",
    },
  },
  {
    id: "arabic-strong",
    name: "Arabic Bold",
    description: "مناسب للمحتوى العربي",
    patch: {
      fontFamily: "Noto Sans Arabic",
      color: "#FFFFFF",
      bg_enabled: true,
      bg_color: "#13131c",
      bg_opacity: 0.7,
      shadow: 2,
      outline_enabled: true,
      outline_color: "#000000",
      caption_animation: "none",
    },
  },
]

