// Caption style presets — each maps to the backend StyleOptions schema.
// The `preview` object drives the visual mock shown in the picker.

export const STYLE_PRESETS = [
  {
    id: "classic",
    name: "كلاسيك",
    hint: "نص أبيض على خلفية سوداء — مظهر تقليدي",
    style: {
      font_size_pct: 5.5,
      color: "#FFFFFF",
      bg_enabled: true,
      bg_color: "#000000",
      bg_opacity: 0.55,
      shadow: 2,
      outline_enabled: false,
      outline_color: "#000000",
      position: "bottom-center",
      caption_animation: "none",
      karaoke_color: "#FF9F43",
    },
    preview: {
      text: "بسم الله الرحمن الرحيم",
      activeWordIndex: -1,
      textClass: "text-white font-extrabold",
      bgClass: "bg-black/55 px-3 py-1.5 rounded-md",
      outline: false,
      animate: false,
    },
  },
  {
    id: "bold",
    name: "بولد",
    hint: "نص ضخم بحدّ أسود سميك — بدون خلفية",
    style: {
      font_size_pct: 7.0,
      color: "#FFFFFF",
      bg_enabled: false,
      bg_color: "#000000",
      bg_opacity: 0,
      shadow: 0,
      outline_enabled: true,
      outline_color: "#000000",
      position: "bottom-center",
      caption_animation: "fade",
      karaoke_color: "#FF9F43",
    },
    preview: {
      text: "كلام جامد ومتركّز",
      activeWordIndex: -1,
      textClass: "text-white font-black text-[16px]",
      bgClass: "px-1",
      outline: true,
      animate: false,
    },
  },
  {
    id: "karaoke",
    name: "كاراوكي",
    hint: "الكلمة المنطوقة تتلوّن بلون مختلف",
    style: {
      font_size_pct: 6.0,
      color: "#FFFFFF",
      bg_enabled: true,
      bg_color: "#000000",
      bg_opacity: 0.5,
      shadow: 1,
      outline_enabled: false,
      outline_color: "#000000",
      position: "bottom-center",
      caption_animation: "karaoke",
      karaoke_color: "#FF9F43",
    },
    preview: {
      text: "الكلمة دي بتنوّر",
      activeWordIndex: 2,
      textClass: "text-white font-extrabold",
      bgClass: "bg-black/55 px-3 py-1.5 rounded-md",
      outline: false,
      animate: false,
      activeColor: "#FF9F43",
    },
  },
  {
    id: "pop",
    name: "بوب",
    hint: "الكلمات تظهر واحدة واحدة بحركة دخول",
    style: {
      font_size_pct: 7.5,
      color: "#FFFFFF",
      bg_enabled: true,
      bg_color: "#FF6B6B",
      bg_opacity: 0.9,
      shadow: 2,
      outline_enabled: false,
      outline_color: "#000000",
      position: "bottom-center",
      caption_animation: "word",
      karaoke_color: "#FFFFFF",
    },
    preview: {
      text: "كلمة",
      activeWordIndex: 0,
      textClass: "text-white font-black text-[18px]",
      bgClass: "px-3 py-1.5 rounded-md",
      bgStyle: { background: "#FF6B6B" },
      outline: false,
      animate: true,
    },
  },
]

export function getPresetById(id) {
  return STYLE_PRESETS.find((p) => p.id === id) || STYLE_PRESETS[0]
}
