// Caption style presets — each maps to the backend StyleOptions schema.
// The `preview` object drives the visual mock shown in the picker.

export const STYLE_PRESETS = [
  {
    id: "classic",
    name: "كلاسيك",
    hint: "نص أبيض على خلفية سوداء — مظهر تقليدي",
    style: {
      fontFamily: "Noto Sans Arabic",
      font_size_pct: 6.0,
      color: "#FFFFFF",
      bg_enabled: true,
      bg_color: "#000000",
      bg_opacity: 0.65,
      shadow: 2,
      outline_enabled: false,
      outline_color: "#000000",
      position: "bottom-center",
      caption_animation: "none",
      karaoke_color: "#FF9F43",
    },
    preview: {
      text: "بسم الله الرحمن الرحيم",
      activeWordIndex: -1,
      textClass: "text-white font-bold",
      bgClass: "bg-black/65 px-3 py-1.5 rounded-md",
      outline: false,
      animate: false,
    },
  },
  {
    id: "bold",
    name: "بولد",
    hint: "نص أصفر ضخم بحدّ أسود سميك — بدون خلفية",
    style: {
      fontFamily: "Cairo",
      font_size_pct: 8.5,
      color: "#FDE047",
      bg_enabled: false,
      bg_color: "#000000",
      bg_opacity: 0,
      shadow: 3,
      outline_enabled: true,
      outline_color: "#000000",
      position: "center",
      caption_animation: "fade",
      karaoke_color: "#FF9F43",
    },
    preview: {
      text: "كلام جامد ومتركّز",
      activeWordIndex: -1,
      textClass: "text-[#FDE047] font-black text-[18px]",
      bgClass: "px-1",
      outline: true,
      animate: false,
    },
  },
  {
    id: "karaoke",
    name: "كاراوكي",
    hint: "الكلمة المنطوقة تتلوّن بأخضر فاقع",
    style: {
      fontFamily: "Tajawal",
      font_size_pct: 7.0,
      color: "#FFFFFF",
      bg_enabled: true,
      bg_color: "#000000",
      bg_opacity: 0.8,
      shadow: 2,
      outline_enabled: false,
      outline_color: "#000000",
      position: "bottom-center",
      caption_animation: "karaoke",
      karaoke_color: "#4ADE80",
    },
    preview: {
      text: "الكلمة دي بتنوّر",
      activeWordIndex: 2,
      textClass: "text-white font-extrabold",
      bgClass: "bg-black/80 px-3 py-2 rounded-lg",
      outline: false,
      animate: false,
      activeColor: "#4ADE80",
    },
  },
  {
    id: "pop",
    name: "بوب",
    hint: "كلمة بكلمة مع خلفية ملونة",
    style: {
      fontFamily: "Cairo",
      font_size_pct: 9.0,
      color: "#FFFFFF",
      bg_enabled: true,
      bg_color: "#EF4444",
      bg_opacity: 1.0,
      shadow: 4,
      outline_enabled: false,
      outline_color: "#000000",
      position: "center",
      caption_animation: "word",
      karaoke_color: "#FFFFFF",
    },
    preview: {
      text: "كلمة",
      activeWordIndex: 0,
      textClass: "text-white font-black text-[20px]",
      bgClass: "px-4 py-2 rounded-xl",
      bgStyle: { background: "#EF4444" },
      outline: false,
      animate: true,
    },
  },
]

export function getPresetById(id) {
  return STYLE_PRESETS.find((p) => p.id === id) || STYLE_PRESETS[0]
}
